/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class CircleShape extends Shape {
  private long swigCPtr;

  protected CircleShape(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.CircleShape_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CircleShape obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_CircleShape(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CircleShape() {
    this(liquidfunJNI.new_CircleShape(), true);
  }

  public void setPosition(float x, float y) {
    liquidfunJNI.CircleShape_setPosition(swigCPtr, this, x, y);
  }

  public float getPositionX() {
    return liquidfunJNI.CircleShape_getPositionX(swigCPtr, this);
  }

  public float getPositionY() {
    return liquidfunJNI.CircleShape_getPositionY(swigCPtr, this);
  }

}
