/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class EdgeShape extends Shape {
  private long swigCPtr;

  protected EdgeShape(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.EdgeShape_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EdgeShape obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_EdgeShape(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public EdgeShape() {
    this(liquidfunJNI.new_EdgeShape(), true);
  }

  public void set(float vx1, float vy1, float vx2, float vy2) {
    liquidfunJNI.EdgeShape_set(swigCPtr, this, vx1, vy1, vx2, vy2);
  }

}
