/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public interface liquidfunConstants {
  public final static int B2_ASSERT_ENABLED = liquidfunJNI.B2_ASSERT_ENABLED_get();
  public final static double _pi = liquidfunJNI._pi_get();
  public final static int LIQUIDFUN_EXTERNAL_LANGUAGE_API = liquidfunJNI.LIQUIDFUN_EXTERNAL_LANGUAGE_API_get();
  public final static int _maxManifoldPoints = liquidfunJNI._maxManifoldPoints_get();
  public final static int _maxPolygonVertices = liquidfunJNI._maxPolygonVertices_get();
  public final static double _aabbExtension = liquidfunJNI._aabbExtension_get();
  public final static double _aabbMultiplier = liquidfunJNI._aabbMultiplier_get();
  public final static double _linearSlop = liquidfunJNI._linearSlop_get();
  public final static double _angularSlop = liquidfunJNI._angularSlop_get();
  public final static double _polygonRadius = liquidfunJNI._polygonRadius_get();
  public final static int _maxSubSteps = liquidfunJNI._maxSubSteps_get();
  public final static int _maxTOIContacts = liquidfunJNI._maxTOIContacts_get();
  public final static double _velocityThreshold = liquidfunJNI._velocityThreshold_get();
  public final static double _maxLinearCorrection = liquidfunJNI._maxLinearCorrection_get();
  public final static double _maxAngularCorrection = liquidfunJNI._maxAngularCorrection_get();
  public final static double _maxTranslation = liquidfunJNI._maxTranslation_get();
  public final static double _maxTranslationSquared = liquidfunJNI._maxTranslationSquared_get();
  public final static double _maxRotation = liquidfunJNI._maxRotation_get();
  public final static double _maxRotationSquared = liquidfunJNI._maxRotationSquared_get();
  public final static double _baumgarte = liquidfunJNI._baumgarte_get();
  public final static double _toiBaugarte = liquidfunJNI._toiBaugarte_get();
  public final static int _invalidParticleIndex = liquidfunJNI._invalidParticleIndex_get();
  public final static int _maxParticleIndex = liquidfunJNI._maxParticleIndex_get();
  public final static double _particleStride = liquidfunJNI._particleStride_get();
  public final static double _minParticleWeight = liquidfunJNI._minParticleWeight_get();
  public final static double _maxParticlePressure = liquidfunJNI._maxParticlePressure_get();
  public final static double _maxParticleForce = liquidfunJNI._maxParticleForce_get();
  public final static int _maxTriadDistance = liquidfunJNI._maxTriadDistance_get();
  public final static int _maxTriadDistanceSquared = liquidfunJNI._maxTriadDistanceSquared_get();
  public final static int _minParticleSystemBufferCapacity = liquidfunJNI._minParticleSystemBufferCapacity_get();
  public final static double _barrierCollisionTime = liquidfunJNI._barrierCollisionTime_get();
  public final static double _timeToSleep = liquidfunJNI._timeToSleep_get();
  public final static double _linearSleepTolerance = liquidfunJNI._linearSleepTolerance_get();
  public final static double _angularSleepTolerance = liquidfunJNI._angularSleepTolerance_get();
}
