/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class ParticleGroup {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ParticleGroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParticleGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public ParticleGroup getNext() {
    long cPtr = liquidfunJNI.ParticleGroup_getNext(swigCPtr, this);
    return (cPtr == 0) ? null : new ParticleGroup(cPtr, false);
  }

  public int getParticleCount() {
    return liquidfunJNI.ParticleGroup_getParticleCount(swigCPtr, this);
  }

  public int getBufferIndex() {
    return liquidfunJNI.ParticleGroup_getBufferIndex(swigCPtr, this);
  }

  public int getGroupFlags() {
    return liquidfunJNI.ParticleGroup_getGroupFlags(swigCPtr, this);
  }

}
