/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.fpl.liquidfun;

public class PolygonShape extends Shape {
  private long swigCPtr;

  protected PolygonShape(long cPtr, boolean cMemoryOwn) {
    super(liquidfunJNI.PolygonShape_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PolygonShape obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        liquidfunJNI.delete_PolygonShape(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PolygonShape() {
    this(liquidfunJNI.new_PolygonShape(), true);
  }

  public void setAsBox(float hx, float hy) {
    liquidfunJNI.PolygonShape_setAsBox__SWIG_0(swigCPtr, this, hx, hy);
  }

  public void setCentroid(float x, float y) {
    liquidfunJNI.PolygonShape_setCentroid(swigCPtr, this, x, y);
  }

  public void setAsBox(float hx, float hy, float centerX, float centerY, float angle) {
    liquidfunJNI.PolygonShape_setAsBox__SWIG_1(swigCPtr, this, hx, hy, centerX, centerY, angle);
  }

  public void set(float[] vertices, int count) {
    liquidfunJNI.PolygonShape_set(swigCPtr, this, vertices, count);
  }

}
